### ISSUE TITLE
Fortnite and Switch online bypass..

### ISSUE THREAD

**Issue by Detr0x** [jjolano/shadow#2]
Apps like Fortnite and Switch online takes a screenshot of / (root) and then checks its files in the apps sandbox by making a symlink of / (root). Can this be bypassed...??

**Comment by jjolano** [comment]
Is that how it works? Interesting..

There is a method provided by the SDK to resolve symlinks, so maybe I'll play around with that?

**Comment by Detr0x** [comment]
Perfect awesome...!

**Comment by Detr0x** [comment]
Do keep me updated....!

**Comment by Detr0x** [comment]
Fortnite has multiple levels of jb detection..!
In the begining stage it detects whether or not there is a folder called “jb” in / (root). If yes it gives an error saying modified os after jumping from the battle bus.
In the second stage it does the file check as described in the title (presumably) even that is after jumping from the battle bus..!
(Atleast the error comes after that).

**Comment by jjolano** [comment]
I have added functionality in an upcoming major release for Shadow to track and internally resolve symlinks. Hopefully it works.

**Comment by Detr0x** [comment]
Could you test it once with fortnite and Switch online so that we can be sure of its functionality....!

**Comment by tdzard94** [comment]
some app check jb by asembly
when i restart my phone, app still throw jailbreak error

**Comment by jjolano** [comment]
Switch doesn't seem to be using any symlinks.. but it seems to be detecting loaded libraries in a very low level way.

Leaving this here for reference later ;) https://opensource.apple.com/source/xnu/xnu-4570.41.2/osfmk/mach/task_info.h.auto.html

**Comment by Detr0x** [comment]
And what about fortnite...?

**Comment by Detr0x** [comment]
Also https://twitter.com/tri___angle/status/1131491156171210752
@tri___angle seems to have confirmed that switch online uses / symlink method...

**Comment by jjolano** [comment]
well.. I hooked all symlink methods (both libc and NSFileManager methods) that I know of and didn't get any log about it 🤔 

Didn't test fortnite yet, my phone is quite full from all the various apps installed to test detection 👀

**Comment by jjolano** [comment]
I have released version 2.0 for now.

**Comment by Detr0x** [comment]
I’ll check Fortnite with it..!

**Comment by Detr0x** [comment]
Well Fortnite still doesn’t work...!
🥺
Fortnite seems to be on a different level itself when it comes to detection. I really hope you could get some time and space to defeat this app once and for all...! It has been undefeated for a long time now..!

**Comment by Detr0x** [comment]
I’ve donated to you cuz i really like tge efforts you are making to help people...! Keep it up. Hopefully someday you’ll defeat FORTNITE... 🤣
