### ISSUE TITLE
Runtime Symbol Lookups caused crash in 3.3.2 while 3.0-0.rc3 is not

### ISSUE THREAD

**Issue by yur1xpp** [jjolano/shadow#63]
Hey, I just whipped up my jailbroken device since installed 3.0-0.rc3, and I upgraded the tweak today to 3.3.2. However, [Shopee](https://apps.apple.com/my/app/shopee-my-12-12-birthday-sale/id959841113)  (Malaysia Store) crashed if "Runtime Symbol Lookups" is enabled, but not in 3.0-0.rc3. There's no crash log produced from this. Do you have any idea?

iPhone X, iOS 14.3, Substitute

Thanks!

EDIT:
This same app also crashed in all version whenever "Loaded Modules" is enabled, I wonder if you would be able to take a look a it too?

**Comment by jjolano** [comment]
Currently looking into the Loaded Modules crashes. Unfortunately I don't have that app in my region. Would you be able to provide the IPA?

**Comment by yur1xpp** [comment]
Of course! Thank you for trying to look into this, much appreciated!

Here's the IPA with app thinning disabled:
https://www.dropbox.com/s/792x1vzcrqbolv8/decrypted-shopee-2.95.56.ipa?dl=0

**Comment by jjolano** [comment]
Thanks, I can confirm a crash on my device with the Runtime Symbol Lookups hook. Luckily I am able to get a crash log.

**Comment by jjolano** [comment]
Should be fixed in v3.3.3

**Comment by yur1xpp** [comment]
Can confirm the symbol lookups now works! Thanks very much!

I think we shall still leave this open too since Loaded Modules is probably not fixed yet?

**Comment by jjolano** [comment]
It happens to work under libhooker, but testing it again with Substitute is giving me a crash unrelated to Loaded Modules. Let's keep it open for now

**Comment by jjolano** [comment]
And testing again is working under Substitute. Now I'm confused. Would you happen to have a cr4shed log?

**Comment by keldey** [comment]
I tested the app on Substitute and it doesn’t crash with loaded modules or any options enabled either. v3.3.3 has fixed all the detection and crashing problems I faced upgrading from v2

**Comment by yur1xpp** [comment]
That's weird, it crashed for me whenever it's enabled. I do have crash log for this actually.

```
Date: 12/3/22, 10:39 AM
Process: ShopeeMY
Bundle id: com.beeasy.shopee.my
Device: iPhone X, iOS 14.3
Bundle version: 2.95.59

Exception type: EXC_SOFTWARE (SIGABRT)
Exception subtype: EXC_UNIX_ABORT
Exception codes: 0x0000000000010002, 0x0000000000000000
Culprit: Shadow.dylib

Triggered by thread: 0
Thread name: Dispatch queue: com.apple.main-thread
Call stack:
0   libsystem_kernel.dylib        	0x00000001daf3484c 0x1daf0d000 + 161868     	// __pthread_kill
1   libsystem_pthread.dylib       	0x00000001f777a9e8 0x1f7770000 + 43496      	// pthread_kill
2   libsystem_c.dylib             	0x00000001b7dc38f4 0x1b7d50000 + 473332     	// abort
3   libsubstitute.dylib           	0x000000010c7bf3ec 0x10c7ac000 + 78828      	// SubHookMemory.cold.1
4   libsubstitute.dylib           	0x000000010c7bc678 0x10c7ac000 + 67192      	// SubHookMemory
5   Shadow.dylib                  	0x0000000110453edc 0x110440000 + 81628      	// shadowhook_dyld
6   Shadow.dylib                  	0x000000011045f4d0 0x110440000 + 128208     	// func_1e744
7   dyld                          	0x000000010b3ac810 0x10b394000 + 100368     	// ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&)
8   dyld                          	0x000000010b3acbd8 0x10b394000 + 101336     	// ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&)
9   dyld                          	0x000000010b3a7600 0x10b394000 + 79360      	// ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&)
10  dyld                          	0x000000010b3a5878 0x10b394000 + 71800      	// ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&)
11  dyld                          	0x000000010b3a5940 0x10b394000 + 72000      	// ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&)
12  dyld                          	0x000000010b39a1c8 0x10b394000 + 25032      	// dyld::runInitializers(ImageLoader*)
13  dyld                          	0x000000010b3a18fc 0x10b394000 + 55548      	// dlopen_internal
14  libdyld.dylib                 	0x00000001aed315d0 0x1aed2c000 + 21968      	// dlopen_internal(char const*, int, void*)
15  substitute-loader.dylib       	0x000000010cd61ad8 0x10cb00000 + 2497240    
16  substitute-loader.dylib       	0x000000010cd61af8 0x10cb00000 + 2497272    
17  substitute-loader.dylib       	0x000000010cd61b18 0x10cb00000 + 2497304    
18  substitute-loader.dylib       	0x000000010cd29358 0x10cb00000 + 2265944    
19  substitute-loader.dylib       	0x000000010cc66da4 0x10cb00000 + 1469860    
20  substitute-loader.dylib       	0x000000010cc66064 0x10cb00000 + 1466468    
21  substitute-loader.dylib       	0x000000010ccd3d88 0x10cb00000 + 1916296    
22  substitute-loader.dylib       	0x000000010cc6c62c 0x10cb00000 + 1492524    
23  dyld                          	0x000000010b3ac810 0x10b394000 + 100368     	// ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&)
24  dyld                          	0x000000010b3acbd8 0x10b394000 + 101336     	// ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&)
25  dyld                          	0x000000010b3a7600 0x10b394000 + 79360      	// ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&)
26  dyld                          	0x000000010b3a5878 0x10b394000 + 71800      	// ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&)
27  dyld                          	0x000000010b3a5940 0x10b394000 + 72000      	// ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&)
28  dyld                          	0x000000010b39a1c8 0x10b394000 + 25032      	// dyld::runInitializers(ImageLoader*)
29  dyld                          	0x000000010b3a18fc 0x10b394000 + 55548      	// dlopen_internal
30  libdyld.dylib                 	0x00000001aed315d0 0x1aed2c000 + 21968      	// dlopen_internal(char const*, int, void*)
31  substitute-inserter.dylib     	0x000000010b55d284 0x10b480000 + 905860     	// func_dcd7c
32  substitute-inserter.dylib     	0x000000010b86aac0 0x10b480000 + 4106944    	// func_3eaab4
33  substitute-inserter.dylib     	0x000000010b82b980 0x10b480000 + 3848576    	// func_3a1afc
34  dyld                          	0x000000010b3ac810 0x10b394000 + 100368     	// ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&)
35  dyld                          	0x000000010b3acbd8 0x10b394000 + 101336     	// ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&)
36  dyld                          	0x000000010b3a7600 0x10b394000 + 79360      	// ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&)
37  dyld                          	0x000000010b3a5878 0x10b394000 + 71800      	// ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&)
38  dyld                          	0x000000010b3a5940 0x10b394000 + 72000      	// ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&)
39  dyld                          	0x000000010b396688 0x10b394000 + 9864       	// dyld::initializeMainExecutable()
40  dyld                          	0x000000010b39b928 0x10b394000 + 31016      	// dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*)
41  dyld                          	0x000000010b395208 0x10b394000 + 4616       	// dyldbootstrap::start(dyld3::MachOLoaded const*, int, char const**, dyld3::MachOLoaded const*, unsigned long*)
42  dyld                          	0x000000010b395038 0x10b394000 + 4152       	// _dyld_start

Register values:
PC: 0x0                 LR: 0x0                 CPSR: 0x0
x0: 0x0                 x1: 0x0                 x2: 0x0
x3: 0x0                 x4: 0x0                 x5: 0x0
x6: 0x0                 x7: 0x0                 x8: 0x0
x9: 0x0                 x10: 0x0                x11: 0x0
x12: 0x0                x13: 0x0                x14: 0x0
x15: 0x0                x16: 0x0                x17: 0x0
x18: 0x0                x19: 0x0                x20: 0x0
x21: 0x0                x22: 0x0                x23: 0x0
x24: 0x0                x25: 0x0                x26: 0x0
x27: 0x0                x28: 0x0

Loaded images:
0: /var/containers/Bundle/Application/0747035A-147E-41E6-96CD-1745DD92159D/ShopeeMY.app/ShopeeMY
1: /var/containers/Bundle/Application/0747035A-147E-41E6-96CD-1745DD92159D/ShopeeMY.app/Frameworks/SNNEngine.framework/SNNEngine
2: /var/containers/Bundle/Application/0747035A-147E-41E6-96CD-1745DD92159D/ShopeeMY.app/Frameworks/Sargeras.framework/Sargeras
3: /var/containers/Bundle/Application/0747035A-147E-41E6-96CD-1745DD92159D/ShopeeMY.app/Frameworks/euler.framework/euler
4: /usr/lib/dyld
5: /usr/lib/substitute-inserter.dylib
6: /var/containers/Bundle/Application/0747035A-147E-41E6-96CD-1745DD92159D/ShopeeMY.app/Frameworks/Cronet.framework/Cronet
7: /var/containers/Bundle/Application/0747035A-147E-41E6-96CD-1745DD92159D/ShopeeMY.app/Frameworks/SSZRTC.framework/SSZRTC
8: /usr/lib/libobjc-trampolines.dylib
9: /usr/lib/libsubstitute.dylib
10: /usr/lib/libsubstrate.dylib
11: /Library/MobileSubstrate/DynamicLibraries/   Choicy.dylib
12: /usr/lib/substitute-loader.dylib
13: /Library/MobileSubstrate/DynamicLibraries/ Crane.dylib
14: /Library/MobileSubstrate/DynamicLibraries/0Cr4shed.dylib
15: /usr/lib/libmryipc.dylib
16: /Library/MobileSubstrate/DynamicLibraries/ADockX.dylib
17: /usr/lib/librocketbootstrap.dylib
18: /usr/lib/libsparkcolourpicker.dylib
19: /Library/PreferenceBundles/DockXPrefs.bundle/DockXPrefs
20: /Library/MobileSubstrate/DynamicLibraries/AppSyncUnified-FrontBoard.dylib
21: /usr/lib/libactivator.dylib
22: /Library/MobileSubstrate/DynamicLibraries/AutoAlerts.dylib
23: /Library/MobileSubstrate/DynamicLibraries/Boardy.dylib
24: /Library/Frameworks/Cephei.framework/Cephei
25: /usr/lib/CepheiUI.framework/CepheiUI
26: /Library/MobileSubstrate/DynamicLibraries/DictMojiX.dylib
27: /Library/MobileSubstrate/DynamicLibraries/EmojiPortPE.dylib
28: /Library/MobileSubstrate/DynamicLibraries/EmojiPort/EmojiAttributes.dylib
29: /usr/lib/libundirect.dylib
30: /Library/MobileSubstrate/DynamicLibraries/EmojiPort/EmojiPortPEReal.dylib
31: /usr/lib/libEmojiLibrary.dylib
32: /Library/MobileSubstrate/DynamicLibraries/FLEXing.dylib
33: /Library/MobileSubstrate/DynamicLibraries/libFLEX.dylib
34: /Library/MobileSubstrate/DynamicLibraries/Flex.dylib
36: /Library/MobileSubstrate/DynamicLibraries/KB2Change.dylib
37: /usr/lib/libstdc++.6.dylib
38: /Library/MobileSubstrate/DynamicLibraries/NoCShare.dylib
40: /Library/MobileSubstrate/DynamicLibraries/Shadow.dylib
41: /usr/lib/libsandy.dylib
42: /usr/lib/system/libdispatch.dylib
43: /usr/lib/system/libdyld.dylib
44: /usr/lib/libicucore.A.dylib
45: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
46: /System/Library/Frameworks/CoreServices.framework/CoreServices
47: /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/WirelessDiagnostics
48: /System/Library/Frameworks/SystemConfiguration.framework/SystemConfiguration
49: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
50: /System/Library/Frameworks/CFNetwork.framework/CFNetwork
51: /usr/lib/libnetwork.dylib
52: /System/Library/Frameworks/Accounts.framework/Accounts
53: /System/Library/Frameworks/Foundation.framework/Foundation
54: /System/Library/Frameworks/ImageIO.framework/ImageIO
55: /System/Library/Frameworks/CoreGraphics.framework/CoreGraphics
56: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
57: /usr/lib/libAccessibility.dylib
58: /System/Library/Frameworks/QuartzCore.framework/QuartzCore
59: /System/Library/PrivateFrameworks/BackBoardServices.framework/BackBoardServices
60: /System/Library/PrivateFrameworks/TextInput.framework/TextInput
61: /System/Library/PrivateFrameworks/AppleMediaServices.framework/AppleMediaServices
62: /usr/lib/swift/libswiftFoundation.dylib
63: /usr/lib/swift/libswiftCore.dylib
64: /System/Library/PrivateFrameworks/UIKitServices.framework/UIKitServices
65: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
66: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
67: /System/Library/Frameworks/CoreText.framework/CoreText
68: /System/Library/PrivateFrameworks/ExtensionKit.framework/ExtensionKit
69: /System/Library/PrivateFrameworks/ChronoServices.framework/ChronoServices
70: /System/Library/PrivateFrameworks/BaseBoard.framework/BaseBoard
71: /System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
72: /System/Library/Frameworks/Contacts.framework/Contacts
73: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
74: /System/Library/Frameworks/CoreLocation.framework/CoreLocation
75: /System/Library/Frameworks/CloudKit.framework/CloudKit
76: /System/Library/Frameworks/CoreData.framework/CoreData
77: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
78: /usr/lib/swift/libswiftCoreGraphics.dylib
79: /System/Library/PrivateFrameworks/AppSupport.framework/AppSupport
80: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
81: /System/Library/PrivateFrameworks/IMFoundation.framework/IMFoundation
82: /System/Library/PrivateFrameworks/IDS.framework/IDS
83: /System/Library/Frameworks/Security.framework/Security
84: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
85: /System/Library/PrivateFrameworks/AudioSession.framework/AudioSession
86: /System/Library/PrivateFrameworks/AVFCore.framework/AVFCore
87: /System/Library/Frameworks/Intents.framework/Intents
88: /System/Library/Frameworks/CoreImage.framework/CoreImage
89: /System/Library/PrivateFrameworks/ColorSync.framework/ColorSync
90: /System/Library/Frameworks/CoreVideo.framework/CoreVideo
91: /System/Library/Frameworks/MediaToolbox.framework/MediaToolbox
92: /System/Library/Frameworks/CoreMedia.framework/CoreMedia
93: /System/Library/Frameworks/AudioToolbox.framework/AudioToolbox
94: /System/Library/Frameworks/CoreHaptics.framework/CoreHaptics
95: /System/Library/PrivateFrameworks/UserActivity.framework/UserActivity
96: /System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation
97: /usr/lib/system/libsystem_info.dylib
98: /usr/lib/system/libsystem_c.dylib
99: /System/Library/PrivateFrameworks/RunningBoardServices.framework/RunningBoardServices
100: /System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore
101: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
102: /System/Library/PrivateFrameworks/ContactsFoundation.framework/ContactsFoundation
103: /System/Library/Frameworks/HealthKit.framework/HealthKit
104: /System/Library/PrivateFrameworks/ProactiveEventTracker.framework/ProactiveEventTracker
105: /System/Library/PrivateFrameworks/Lexicon.framework/Lexicon
106: /System/Library/PrivateFrameworks/PersonalizationPortrait.framework/PersonalizationPortrait
107: /System/Library/PrivateFrameworks/CoreDuetContext.framework/CoreDuetContext
108: /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
109: /System/Library/PrivateFrameworks/DataMigration.framework/DataMigration
110: /System/Library/PrivateFrameworks/SpringBoardServices.framework/SpringBoardServices
111: /System/Library/PrivateFrameworks/ContextKit.framework/ContextKit
112: /System/Library/Frameworks/CoreMotion.framework/CoreMotion
113: /System/Library/Frameworks/EventKit.framework/EventKit
114: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
115: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
116: /System/Library/PrivateFrameworks/CoreUtils.framework/CoreUtils
117: /System/Library/PrivateFrameworks/FamilyCircle.framework/FamilyCircle
118: /System/Library/Frameworks/CoreSpotlight.framework/CoreSpotlight
119: /System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
120: /System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
121: /System/Library/PrivateFrameworks/SafariSafeBrowsing.framework/SafariSafeBrowsing
122: /System/Library/Frameworks/WebKit.framework/WebKit
123: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
124: /usr/lib/libMobileGestalt.dylib
125: /System/Library/PrivateFrameworks/CommonUtilities.framework/CommonUtilities
126: /System/Library/PrivateFrameworks/IDSFoundation.framework/IDSFoundation
127: /System/Library/PrivateFrameworks/IMSharedUtilities.framework/IMSharedUtilities
128: /System/Library/PrivateFrameworks/CoreSuggestions.framework/CoreSuggestions
129: /System/Library/PrivateFrameworks/AddressBookLegacy.framework/AddressBookLegacy
130: /System/Library/Frameworks/UserNotifications.framework/UserNotifications
131: /System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
132: /usr/lib/system/libsystem_malloc.dylib
133: /System/Library/Frameworks/MapKit.framework/MapKit
134: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
135: /System/Library/PrivateFrameworks/AuthKit.framework/AuthKit
136: /System/Library/PrivateFrameworks/AppleAccount.framework/AppleAccount
137: /System/Library/Frameworks/AVFoundation.framework/Frameworks/AVFAudio.framework/AVFAudio
138: /System/Library/PrivateFrameworks/AudioToolboxCore.framework/AudioToolboxCore
139: /System/Library/PrivateFrameworks/StoreServices.framework/StoreServices
140: /System/Library/PrivateFrameworks/Sharing.framework/Sharing
141: /System/Library/PrivateFrameworks/ShareSheet.framework/ShareSheet
142: /System/Library/PrivateFrameworks/CoreParsec.framework/CoreParsec
143: /System/Library/PrivateFrameworks/PhotoFoundation.framework/PhotoFoundation
144: /System/Library/Frameworks/Photos.framework/Photos
145: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
146: /System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices
147: /System/Library/PrivateFrameworks/MobileBackup.framework/MobileBackup
148: /System/Library/PrivateFrameworks/MSUDataAccessor.framework/MSUDataAccessor
149: /System/Library/PrivateFrameworks/MobileAsset.framework/MobileAsset
150: /usr/lib/system/libsystem_networkextension.dylib
151: /System/Library/Frameworks/NetworkExtension.framework/NetworkExtension
152: /System/Library/Frameworks/CoreML.framework/CoreML
153: /System/Library/PrivateFrameworks/Espresso.framework/Espresso
154: /System/Library/Frameworks/VideoToolbox.framework/VideoToolbox
155: /System/Library/PrivateFrameworks/OnBoardingKit.framework/OnBoardingKit
156: /System/Library/PrivateFrameworks/AXCoreUtilities.framework/AXCoreUtilities
157: /System/Library/PrivateFrameworks/Montreal.framework/Montreal
158: /System/Library/PrivateFrameworks/LanguageModeling.framework/LanguageModeling
159: /System/Library/PrivateFrameworks/InternationalSupport.framework/InternationalSupport
160: /System/Library/PrivateFrameworks/iTunesCloud.framework/iTunesCloud
161: /usr/lib/swift/libswiftUIKit.dylib
162: /System/Library/PrivateFrameworks/CarKit.framework/CarKit
163: /System/Library/PrivateFrameworks/CalendarDatabase.framework/CalendarDatabase
164: /System/Library/PrivateFrameworks/Notes.framework/Notes
165: /System/Library/Frameworks/LinkPresentation.framework/LinkPresentation
166: /System/Library/Frameworks/Combine.framework/Combine
167: /System/Library/Frameworks/UniformTypeIdentifiers.framework/UniformTypeIdentifiers
168: /System/Library/PrivateFrameworks/CloudDocs.framework/CloudDocs
169: /System/Library/PrivateFrameworks/Message.framework/Message
170: /System/Library/PrivateFrameworks/EmailFoundation.framework/EmailFoundation
171: /System/Library/PrivateFrameworks/FindMyDevice.framework/FindMyDevice
172: /System/Library/PrivateFrameworks/MediaServices.framework/MediaServices
173: /System/Library/PrivateFrameworks/SearchFoundation.framework/SearchFoundation
174: /System/Library/PrivateFrameworks/WebBookmarks.framework/WebBookmarks
175: /usr/lib/libobjc.A.dylib
176: /System/Library/PrivateFrameworks/LoggingSupport.framework/LoggingSupport
177: /usr/lib/libc++.1.dylib
178: /usr/lib/libc++abi.dylib
179: /System/Library/PrivateFrameworks/SetupAssistant.framework/SetupAssistant
180: /System/Library/PrivateFrameworks/OctagonTrust.framework/OctagonTrust
181: /System/Library/PrivateFrameworks/CoreAutoLayout.framework/CoreAutoLayout
182: /System/Library/Frameworks/Network.framework/Network
183: /System/Library/PrivateFrameworks/MobileKeyBag.framework/MobileKeyBag
184: /System/Library/PrivateFrameworks/BaseBoardUI.framework/BaseBoardUI
185: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libvDSP.dylib
186: /usr/lib/libAudioToolboxUtility.dylib
187: /System/Library/PrivateFrameworks/AvatarUI.framework/AvatarUI
188: /System/Library/PrivateFrameworks/CoreNLP.framework/CoreNLP
189: /System/Library/Frameworks/FileProvider.framework/FileProvider
190: /System/Library/PrivateFrameworks/BiomeStorage.framework/BiomeStorage
191: /usr/lib/swift/libswiftDispatch.dylib
192: /System/Library/PrivateFrameworks/DataDetectorsCore.framework/DataDetectorsCore
193: /System/Library/PrivateFrameworks/Symbolication.framework/Symbolication
194: /System/Library/PrivateFrameworks/CrashReporterSupport.framework/CrashReporterSupport
195: /System/Library/PrivateFrameworks/FMCoreLite.framework/FMCoreLite
196: /System/Library/PrivateFrameworks/TelephonyUtilities.framework/TelephonyUtilities
197: /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSNeuralNetwork.framework/MPSNeuralNetwork
198: /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSCore.framework/MPSCore
199: /System/Library/PrivateFrameworks/CalendarFoundation.framework/CalendarFoundation
200: /System/Library/PrivateFrameworks/TipsCore.framework/TipsCore
201: /System/Library/PrivateFrameworks/NLP.framework/NLP
202: /System/Library/PrivateFrameworks/AppSupportUI.framework/AppSupportUI
203: /System/Library/PrivateFrameworks/FTServices.framework/FTServices
204: /System/Library/PrivateFrameworks/ProtocolBuffer.framework/ProtocolBuffer
205: /System/Library/Frameworks/AVKit.framework/AVKit
206: /System/Library/Frameworks/BackgroundTasks.framework/BackgroundTasks
207: /System/Library/PrivateFrameworks/AssertionServices.framework/AssertionServices
208: /System/Library/PrivateFrameworks/CloudServices.framework/CloudServices
209: /System/Library/Frameworks/Metal.framework/Metal
210: /System/Library/PrivateFrameworks/MediaExperience.framework/MediaExperience
211: /System/Library/PrivateFrameworks/VideoProcessing.framework/VideoProcessing
212: /usr/lib/system/libsystem_trace.dylib
213: /System/Library/PrivateFrameworks/CoreServicesInternal.framework/CoreServicesInternal
214: /System/Library/PrivateFrameworks/SafariCore.framework/SafariCore
215: /System/Library/PrivateFrameworks/SafariShared.framework/SafariShared
216: /System/Library/PrivateFrameworks/AppStoreDaemon.framework/AppStoreDaemon
217: /System/Library/PrivateFrameworks/GameCenterUI.framework/GameCenterUI
218: /System/Library/PrivateFrameworks/ContactsAutocompleteUI.framework/ContactsAutocompleteUI
219: /System/Library/Frameworks/MessageUI.framework/MessageUI
220: /System/Library/PrivateFrameworks/SAObjects.framework/SAObjects
221: /System/Library/PrivateFrameworks/VoiceServices.framework/VoiceServices
222: /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
223: /System/Library/PrivateFrameworks/DeviceManagement.framework/DeviceManagement
224: /System/Library/PrivateFrameworks/Translation.framework/Translation
225: /System/Library/PrivateFrameworks/PowerLog.framework/PowerLog
226: /System/Library/PrivateFrameworks/DuetActivityScheduler.framework/DuetActivityScheduler
227: /System/Library/Frameworks/Vision.framework/Vision
228: /System/Library/PrivateFrameworks/DataAccess.framework/DataAccess
229: /System/Library/PrivateFrameworks/ProactiveSupport.framework/ProactiveSupport
230: /System/Library/PrivateFrameworks/ApplePushService.framework/ApplePushService
231: /System/Library/PrivateFrameworks/BoardServices.framework/BoardServices
232: /usr/lib/swift/libswiftCloudKit.dylib
233: /usr/lib/libncurses.5.4.dylib
234: /System/Library/PrivateFrameworks/OSAnalytics.framework/OSAnalytics
235: /System/Library/Frameworks/CoreBluetooth.framework/CoreBluetooth
236: /System/Library/PrivateFrameworks/JetEngine.framework/JetEngine
237: /System/Library/PrivateFrameworks/TemplateKit.framework/TemplateKit
238: /System/Library/PrivateFrameworks/MobileInstallation.framework/MobileInstallation
239: /usr/lib/libTelephonyUtilDynamic.dylib
240: /System/Library/PrivateFrameworks/NanoRegistry.framework/NanoRegistry
241: /System/Library/PrivateFrameworks/SpringBoardFoundation.framework/SpringBoardFoundation
242: /System/Library/PrivateFrameworks/CoreMaterial.framework/CoreMaterial
243: /System/Library/PrivateFrameworks/SpringBoardUIServices.framework/SpringBoardUIServices
244: /usr/lib/libsqlite3.dylib
245: /System/Library/PrivateFrameworks/AVFCapture.framework/AVFCapture
246: /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture
247: /System/Library/PrivateFrameworks/MobileSpotlightIndex.framework/MobileSpotlightIndex
248: /System/Library/PrivateFrameworks/Email.framework/Email
249: /System/Library/Frameworks/EventKitUI.framework/EventKitUI
250: /System/Library/PrivateFrameworks/BulletinBoard.framework/BulletinBoard
251: /System/Library/PrivateFrameworks/PeopleSuggester.framework/PeopleSuggester
252: /usr/lib/system/libsystem_notify.dylib
253: /System/Library/Frameworks/CryptoTokenKit.framework/CryptoTokenKit
254: /usr/lib/system/libcorecrypto.dylib
255: /System/Library/PrivateFrameworks/UserManagement.framework/UserManagement
256: /usr/lib/system/libsystem_asl.dylib
257: /System/Library/PrivateFrameworks/AppSSO.framework/AppSSO
258: /System/Library/PrivateFrameworks/SharedWebCredentials.framework/SharedWebCredentials
259: /System/Library/Frameworks/SafariServices.framework/SafariServices
260: /System/Library/PrivateFrameworks/DataAccessExpress.framework/DataAccessExpress
261: /System/Library/PrivateFrameworks/CoreServicesStore.framework/CoreServicesStore
262: /System/Library/PrivateFrameworks/CoreAnalytics.framework/CoreAnalytics
263: /System/Library/PrivateFrameworks/Symptoms.framework/Frameworks/SymptomAnalytics.framework/SymptomAnalytics
264: /System/Library/PrivateFrameworks/NanoPreferencesSync.framework/NanoPreferencesSync
265: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
266: /System/Library/PrivateFrameworks/IconServices.framework/IconServices
267: /System/Library/Frameworks/QuickLook.framework/QuickLook
268: /System/Library/Frameworks/Accelerate.framework/Frameworks/vImage.framework/vImage
269: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
270: /System/Library/PrivateFrameworks/IAP.framework/IAP
271: /System/Library/PrivateFrameworks/ktrace.framework/ktrace
272: /System/Library/PrivateFrameworks/Celestial.framework/Celestial
273: /System/Library/PrivateFrameworks/TelephonyUI.framework/TelephonyUI
274: /System/Library/PrivateFrameworks/Pegasus.framework/Pegasus
275: /System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy
276: /System/Library/Frameworks/ClassKit.framework/ClassKit
277: /System/Library/Frameworks/StoreKit.framework/StoreKit
278: /System/Library/PrivateFrameworks/IOMobileFramebuffer.framework/IOMobileFramebuffer
279: /System/Library/PrivateFrameworks/ScreenTimeCore.framework/ScreenTimeCore
280: /System/Library/PrivateFrameworks/CoreIDV.framework/CoreIDV
281: /System/Library/PrivateFrameworks/AccountsDaemon.framework/AccountsDaemon
282: /System/Library/PrivateFrameworks/CloudPhotoLibrary.framework/CloudPhotoLibrary
283: /System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
284: /System/Library/Frameworks/CallKit.framework/CallKit
285: /System/Library/PrivateFrameworks/PrototypeTools.framework/PrototypeTools
286: /System/Library/PrivateFrameworks/PersistentConnection.framework/PersistentConnection
287: /System/Library/PrivateFrameworks/BiomeStreams.framework/BiomeStreams
288: /System/Library/Frameworks/PencilKit.framework/PencilKit
289: /usr/lib/swift/libswiftUniformTypeIdentifiers.dylib
290: /System/Library/PrivateFrameworks/CoreSpeech.framework/CoreSpeech
291: /System/Library/PrivateFrameworks/IMDPersistence.framework/IMDPersistence
292: /System/Library/PrivateFrameworks/SafariSharedUI.framework/SafariSharedUI
293: /System/Library/PrivateFrameworks/CoreFollowUp.framework/CoreFollowUp
294: /System/Library/PrivateFrameworks/Rapport.framework/Rapport
295: /System/Library/PrivateFrameworks/SiriUICore.framework/SiriUICore
296: /System/Library/PrivateFrameworks/Categories.framework/Categories
297: /System/Library/PrivateFrameworks/LocationSupport.framework/LocationSupport
298: /System/Library/PrivateFrameworks/iCalendar.framework/iCalendar
299: /System/Library/PrivateFrameworks/CoreAccessories.framework/CoreAccessories
300: /System/Library/PrivateFrameworks/ConfigurationEngineModel.framework/ConfigurationEngineModel
301: /System/Library/PrivateFrameworks/CacheDelete.framework/CacheDelete
302: /System/Library/PrivateFrameworks/CVNLP.framework/CVNLP
303: /System/Library/PrivateFrameworks/AdCore.framework/AdCore
304: /System/Library/PrivateFrameworks/GameCenterFoundation.framework/GameCenterFoundation
305: /System/Library/PrivateFrameworks/OSAServicesClient.framework/OSAServicesClient
306: /System/Library/PrivateFrameworks/BiomeFoundation.framework/BiomeFoundation
307: /System/Library/PrivateFrameworks/ProtectedCloudStorage.framework/ProtectedCloudStorage
308: /System/Library/PrivateFrameworks/C2.framework/C2
309: /System/Library/PrivateFrameworks/DifferentialPrivacy.framework/DifferentialPrivacy
310: /System/Library/PrivateFrameworks/EmbeddedAcousticRecognition.framework/EmbeddedAcousticRecognition
311: /System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
312: /System/Library/PrivateFrameworks/BiometricKit.framework/BiometricKit
313: /System/Library/PrivateFrameworks/CoreSymbolication.framework/CoreSymbolication
314: /System/Library/PrivateFrameworks/Proximity.framework/Proximity
315: /System/Library/PrivateFrameworks/SpeakerRecognition.framework/SpeakerRecognition
316: /System/Library/PrivateFrameworks/MessageSupport.framework/MessageSupport
317: /System/Library/Frameworks/IOSurface.framework/IOSurface
318: /System/Library/PrivateFrameworks/MobileWiFi.framework/MobileWiFi
319: /System/Library/PrivateFrameworks/DoNotDisturb.framework/DoNotDisturb
320: /System/Library/PrivateFrameworks/MMCS.framework/MMCS
321: /System/Library/Frameworks/OpenGLES.framework/libGLImage.dylib
322: /usr/lib/system/libsystem_symptoms.dylib
323: /System/Library/Frameworks/CoreAudio.framework/CoreAudio
324: /System/Library/PrivateFrameworks/ContactsDonation.framework/ContactsDonation
325: /System/Library/PrivateFrameworks/IntentsCore.framework/IntentsCore
326: /System/Library/PrivateFrameworks/FrontBoard.framework/FrontBoard
327: /System/Library/Frameworks/ImageCaptureCore.framework/ImageCaptureCore
328: /System/Library/PrivateFrameworks/RenderBox.framework/RenderBox
329: /System/Library/PrivateFrameworks/Navigation.framework/Navigation
330: /System/Library/PrivateFrameworks/SafariFoundation.framework/SafariFoundation
331: /System/Library/PrivateFrameworks/MaterialKit.framework/MaterialKit
332: /System/Library/PrivateFrameworks/EmojiKit.framework/EmojiKit
333: /System/Library/PrivateFrameworks/CoreAUC.framework/CoreAUC
334: /System/Library/PrivateFrameworks/SettingsFoundation.framework/SettingsFoundation
335: /System/Library/PrivateFrameworks/SiriActivation.framework/SiriActivation
336: /System/Library/PrivateFrameworks/PassKitUIFoundation.framework/PassKitUIFoundation
337: /System/Library/PrivateFrameworks/AccountsUI.framework/AccountsUI
338: /System/Library/PrivateFrameworks/ToneLibrary.framework/ToneLibrary
339: /System/Library/Frameworks/iAd.framework/iAd
340: /System/Library/PrivateFrameworks/MediaSafetyNet.framework/MediaSafetyNet
341: /System/Library/PrivateFrameworks/TimeSync.framework/TimeSync
342: /System/Library/Frameworks/ExposureNotification.framework/ExposureNotification
343: /System/Library/PrivateFrameworks/CoreCDPInternal.framework/CoreCDPInternal
344: /System/Library/PrivateFrameworks/CoreTime.framework/CoreTime
345: /System/Library/PrivateFrameworks/TextRecognition.framework/TextRecognition
346: /System/Library/PrivateFrameworks/JasperDepth.framework/JasperDepth
347: /System/Library/PrivateFrameworks/ContextKitExtraction.framework/ContextKitExtraction
348: /System/Library/PrivateFrameworks/AppleAccountUI.framework/AppleAccountUI
349: /usr/lib/swift/libswiftObjectiveC.dylib
350: /usr/lib/libmorphun.dylib
351: /System/Library/PrivateFrameworks/EmailCore.framework/EmailCore
352: /System/Library/PrivateFrameworks/AVConference.framework/AVConference
353: /System/Library/PrivateFrameworks/KeychainCircle.framework/KeychainCircle
354: /System/Library/PrivateFrameworks/MIME.framework/MIME
355: /System/Library/PrivateFrameworks/MailServices.framework/MailServices
356: /System/Library/PrivateFrameworks/PhotosPlayer.framework/PhotosPlayer
357: /System/Library/PrivateFrameworks/CoreDAV.framework/CoreDAV
358: /System/Library/PrivateFrameworks/CalendarUIKit.framework/CalendarUIKit
359: /System/Library/PrivateFrameworks/MobileIcons.framework/MobileIcons
360: /System/Library/PrivateFrameworks/ProofReader.framework/ProofReader
361: /System/Library/PrivateFrameworks/MallocStackLogging.framework/MallocStackLogging
362: /System/Library/PrivateFrameworks/AttributeGraph.framework/AttributeGraph
363: /System/Library/PrivateFrameworks/EmailDaemon.framework/EmailDaemon
364: /System/Library/PrivateFrameworks/MetadataUtilities.framework/MetadataUtilities
365: /System/Library/PrivateFrameworks/BannerKit.framework/BannerKit
366: /System/Library/PrivateFrameworks/MailSupport.framework/MailSupport
367: /System/Library/PrivateFrameworks/CoreLocationProtobuf.framework/CoreLocationProtobuf
368: /System/Library/PrivateFrameworks/Bom.framework/Bom
369: /System/Library/Frameworks/PushKit.framework/PushKit
370: /System/Library/PrivateFrameworks/PhotosFormats.framework/PhotosFormats
371: /System/Library/PrivateFrameworks/VisualLocalization.framework/VisualLocalization
372: /System/Library/PrivateFrameworks/Quagga.framework/Quagga
373: /System/Library/PrivateFrameworks/StudyLog.framework/StudyLog
374: /System/Library/PrivateFrameworks/ManagedConfigurationUI.framework/ManagedConfigurationUI
375: /System/Library/Frameworks/NaturalLanguage.framework/NaturalLanguage
376: /System/Library/PrivateFrameworks/ARKitCore.framework/ARKitCore
377: /System/Library/PrivateFrameworks/MediaStream.framework/MediaStream
378: /System/Library/PrivateFrameworks/ScreenTimeUI.framework/ScreenTimeUI
379: /System/Library/PrivateFrameworks/JetUI.framework/JetUI
380: /System/Library/PrivateFrameworks/MediaConversionService.framework/MediaConversionService
381: /System/Library/PrivateFrameworks/CoreHandwriting.framework/CoreHandwriting
382: /System/Library/PrivateFrameworks/AppleIDAuthSupport.framework/AppleIDAuthSupport
383: /System/Library/Frameworks/LocalAuthentication.framework/LocalAuthentication
384: /System/Library/PrivateFrameworks/IOAccelerator.framework/IOAccelerator
385: /System/Library/PrivateFrameworks/CloudPhotoServices.framework/CloudPhotoServices
386: /System/Library/PrivateFrameworks/iTunesStore.framework/iTunesStore
387: /usr/lib/system/libsystem_kernel.dylib
388: /System/Library/PrivateFrameworks/ResponseKit.framework/ResponseKit
389: /System/Library/PrivateFrameworks/EmojiFoundation.framework/EmojiFoundation
390: /System/Library/PrivateFrameworks/FontServices.framework/FontServices
391: /System/Library/PrivateFrameworks/AVConference.framework/Frameworks/ViceroyTrace.framework/ViceroyTrace
392: /System/Library/Frameworks/MediaAccessibility.framework/MediaAccessibility
393: /System/Library/PrivateFrameworks/SiriTTS.framework/SiriTTS
394: /System/Library/PrivateFrameworks/SetupAssistantSupport.framework/SetupAssistantSupport
395: /System/Library/Frameworks/Social.framework/Social
396: /System/Library/PrivateFrameworks/VirtualGarage.framework/VirtualGarage
397: /System/Library/PrivateFrameworks/NetAppsUtilities.framework/NetAppsUtilities
398: /System/Library/PrivateFrameworks/Osprey.framework/Osprey
399: /usr/lib/libdscsym.dylib
400: /System/Library/PrivateFrameworks/HangTracer.framework/HangTracer
401: /System/Library/PrivateFrameworks/SampleAnalysis.framework/SampleAnalysis
402: /System/Library/PrivateFrameworks/PlugInKit.framework/PlugInKit
403: /usr/lib/libSystem.B.dylib
404: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
405: /System/Library/PrivateFrameworks/MobileActivation.framework/MobileActivation
406: /System/Library/PrivateFrameworks/CalendarDaemon.framework/CalendarDaemon
407: /usr/lib/libarchive.2.dylib
408: /usr/lib/libtailspin.dylib
409: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libBNNS.dylib
410: /System/Library/Frameworks/LocalAuthentication.framework/Support/SharedUtils.framework/SharedUtils
411: /System/Library/PrivateFrameworks/CoreCDP.framework/CoreCDP
412: /System/Library/PrivateFrameworks/iAdCore.framework/iAdCore
413: /usr/lib/libsysdiagnose.dylib
414: /System/Library/PrivateFrameworks/CoreMediaStream.framework/CoreMediaStream
415: /System/Library/Frameworks/ARKit.framework/ARKit
416: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
417: /System/Library/Frameworks/Accelerate.framework/Accelerate
418: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libBLAS.dylib
419: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libLAPACK.dylib
420: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libLinearAlgebra.dylib
421: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libQuadrature.dylib
422: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libSparse.dylib
423: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libSparseBLAS.dylib
424: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/libvMisc.dylib
425: /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/vecLib
426: /System/Library/Frameworks/AdSupport.framework/AdSupport
427: /System/Library/Frameworks/AddressBook.framework/AddressBook
428: /System/Library/Frameworks/AppTrackingTransparency.framework/AppTrackingTransparency
429: /System/Library/Frameworks/AssetsLibrary.framework/AssetsLibrary
430: /System/Library/Frameworks/AuthenticationServices.framework/AuthenticationServices
431: /System/Library/Frameworks/CarPlay.framework/CarPlay
432: /System/Library/Frameworks/CoreMIDI.framework/CoreMIDI
433: /System/Library/Frameworks/ExternalAccessory.framework/ExternalAccessory
434: /System/Library/Frameworks/GLKit.framework/GLKit
435: /System/Library/Frameworks/GSS.framework/GSS
436: /System/Library/Frameworks/GameController.framework/GameController
437: /System/Library/Frameworks/GameKit.framework/GameKit
438: /System/Library/Frameworks/GameplayKit.framework/GameplayKit
439: /System/Library/Frameworks/IntentsUI.framework/IntentsUI
440: /System/Library/Frameworks/MLCompute.framework/MLCompute
441: /System/Library/Frameworks/Messages.framework/Messages
442: /System/Library/Frameworks/MetalKit.framework/MetalKit
443: /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSImage.framework/MPSImage
444: /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSMatrix.framework/MPSMatrix
445: /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSNDArray.framework/MPSNDArray
446: /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSRayIntersector.framework/MPSRayIntersector
447: /System/Library/Frameworks/MetalPerformanceShaders.framework/MetalPerformanceShaders
448: /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
449: /System/Library/Frameworks/ModelIO.framework/ModelIO
450: /System/Library/Frameworks/OpenAL.framework/OpenAL
451: /System/Library/Frameworks/OpenGLES.framework/OpenGLES
452: /System/Library/Frameworks/OpenGLES.framework/libCVMSPluginSupport.dylib
453: /System/Library/Frameworks/OpenGLES.framework/libCoreFSCache.dylib
454: /System/Library/Frameworks/OpenGLES.framework/libCoreVMClient.dylib
455: /System/Library/Frameworks/OpenGLES.framework/libGFXShared.dylib
456: /System/Library/Frameworks/PDFKit.framework/PDFKit
457: /System/Library/Frameworks/PassKit.framework/PassKit
458: /System/Library/Frameworks/QuickLookThumbnailing.framework/QuickLookThumbnailing
459: /System/Library/Frameworks/ReplayKit.framework/ReplayKit
460: /System/Library/Frameworks/SceneKit.framework/SceneKit
461: /System/Library/Frameworks/SoundAnalysis.framework/SoundAnalysis
462: /System/Library/Frameworks/Speech.framework/Speech
463: /System/Library/Frameworks/SpriteKit.framework/SpriteKit
464: /System/Library/Frameworks/UIKit.framework/UIKit
465: /System/Library/Frameworks/VideoSubscriberAccount.framework/VideoSubscriberAccount
466: /System/Library/Frameworks/Vision.framework/libfaceCore.dylib
467: /System/Library/Frameworks/VisionKit.framework/VisionKit
468: /System/Library/PrivateFrameworks/AFKUser.framework/AFKUser
469: /System/Library/PrivateFrameworks/ANECompiler.framework/ANECompiler
470: /System/Library/PrivateFrameworks/ANEServices.framework/ANEServices
471: /System/Library/PrivateFrameworks/APFS.framework/APFS
472: /System/Library/PrivateFrameworks/ASEProcessing.framework/ASEProcessing
473: /System/Library/PrivateFrameworks/AVConference.framework/Frameworks/ICE.framework/ICE
474: /System/Library/PrivateFrameworks/AVConference.framework/Frameworks/LegacyHandle.framework/LegacyHandle
475: /System/Library/PrivateFrameworks/AVConference.framework/Frameworks/SimpleKeyExchange.framework/SimpleKeyExchange
476: /System/Library/PrivateFrameworks/AVConference.framework/Frameworks/snatmap.framework/snatmap
477: /System/Library/PrivateFrameworks/AdAnalytics.framework/AdAnalytics
478: /System/Library/PrivateFrameworks/AdPlatforms.framework/AdPlatforms
479: /System/Library/PrivateFrameworks/AggregateDictionary.framework/AggregateDictionary
480: /System/Library/PrivateFrameworks/AirPlaySync.framework/AirPlaySync
481: /System/Library/PrivateFrameworks/AlgosScoreFramework.framework/AlgosScoreFramework
482: /System/Library/PrivateFrameworks/AppC3D.framework/AppC3D
483: /System/Library/PrivateFrameworks/AppConduit.framework/AppConduit
484: /System/Library/PrivateFrameworks/AppStoreComponents.framework/AppStoreComponents
485: /System/Library/PrivateFrameworks/AppStoreOverlays.framework/AppStoreOverlays
486: /System/Library/PrivateFrameworks/AppleCV3D.framework/AppleCV3D
487: /System/Library/PrivateFrameworks/AppleCV3DMOVKit.framework/AppleCV3DMOVKit
488: /System/Library/PrivateFrameworks/AppleCV3DModels.framework/AppleCV3DModels
489: /System/Library/PrivateFrameworks/AppleCVA.framework/AppleCVA
490: /System/Library/PrivateFrameworks/AppleDepth.framework/AppleDepth
491: /System/Library/PrivateFrameworks/AppleFSCompression.framework/AppleFSCompression
492: /System/Library/PrivateFrameworks/AppleIDSSOAuthentication.framework/AppleIDSSOAuthentication
493: /System/Library/PrivateFrameworks/AppleJPEG.framework/AppleJPEG
494: /System/Library/PrivateFrameworks/AppleNeuralEngine.framework/AppleNeuralEngine
495: /System/Library/PrivateFrameworks/AppleSauce.framework/AppleSauce
496: /System/Library/PrivateFrameworks/AssetCacheServices.framework/AssetCacheServices
497: /System/Library/PrivateFrameworks/AuthKitUI.framework/AuthKitUI
498: /System/Library/PrivateFrameworks/AutoLoop.framework/AutoLoop
499: /System/Library/PrivateFrameworks/BiomePubSub.framework/BiomePubSub
500: /System/Library/PrivateFrameworks/BluetoothManager.framework/BluetoothManager
501: /System/Library/PrivateFrameworks/BridgePreferences.framework/BridgePreferences
502: /System/Library/PrivateFrameworks/CMCaptureCore.framework/CMCaptureCore
503: /System/Library/PrivateFrameworks/CPAnalytics.framework/CPAnalytics
504: /System/Library/PrivateFrameworks/CPMS.framework/CPMS
505: /System/Library/PrivateFrameworks/CTCarrierSpace.framework/CTCarrierSpace
506: /System/Library/PrivateFrameworks/CameraKit.framework/CameraKit
507: /System/Library/PrivateFrameworks/CaptiveNetwork.framework/CaptiveNetwork
508: /System/Library/PrivateFrameworks/CarPlayUIServices.framework/CarPlayUIServices
509: /System/Library/PrivateFrameworks/Catalyst.framework/Catalyst
510: /System/Library/PrivateFrameworks/CellularPlanManager.framework/CellularPlanManager
511: /System/Library/PrivateFrameworks/CertInfo.framework/CertInfo
512: /System/Library/PrivateFrameworks/CertUI.framework/CertUI
513: /System/Library/PrivateFrameworks/ChunkingLibrary.framework/ChunkingLibrary
514: /System/Library/PrivateFrameworks/CommonAuth.framework/CommonAuth
515: /System/Library/PrivateFrameworks/CommunicationsFilter.framework/CommunicationsFilter
516: /System/Library/PrivateFrameworks/ConstantClasses.framework/ConstantClasses
517: /System/Library/PrivateFrameworks/ContactsAutocomplete.framework/ContactsAutocomplete
518: /System/Library/PrivateFrameworks/ContactsUICore.framework/ContactsUICore
519: /System/Library/PrivateFrameworks/CoreAppleCVA.framework/CoreAppleCVA
520: /System/Library/PrivateFrameworks/CoreBrightness.framework/CoreBrightness
521: /System/Library/PrivateFrameworks/CoreCDPUI.framework/CoreCDPUI
522: /System/Library/PrivateFrameworks/CoreDuetDaemonProtocol.framework/CoreDuetDaemonProtocol
523: /System/Library/PrivateFrameworks/CoreDuetDebugLogging.framework/CoreDuetDebugLogging
524: /System/Library/PrivateFrameworks/CoreEmoji.framework/CoreEmoji
525: /System/Library/PrivateFrameworks/CoreOptimization.framework/CoreOptimization
526: /System/Library/PrivateFrameworks/CorePDF.framework/CorePDF
527: /System/Library/PrivateFrameworks/CorePhoneNumbers.framework/CorePhoneNumbers
528: /System/Library/PrivateFrameworks/CorePrediction.framework/CorePrediction
529: /System/Library/PrivateFrameworks/CoreRE.framework/CoreRE
530: /System/Library/PrivateFrameworks/CoreRecents.framework/CoreRecents
531: /System/Library/PrivateFrameworks/CoreRecognition.framework/CoreRecognition
532: /System/Library/PrivateFrameworks/CoreSDB.framework/CoreSDB
533: /System/Library/PrivateFrameworks/CoreSVG.framework/CoreSVG
534: /System/Library/PrivateFrameworks/DAAPKit.framework/DAAPKit
535: /System/Library/PrivateFrameworks/DCIMServices.framework/DCIMServices
536: /System/Library/PrivateFrameworks/DataDetectorsNaturalLanguage.framework/DataDetectorsNaturalLanguage
537: /System/Library/PrivateFrameworks/DeviceIdentity.framework/DeviceIdentity
538: /System/Library/PrivateFrameworks/DiagnosticLogCollection.framework/DiagnosticLogCollection
539: /System/Library/PrivateFrameworks/DigitalAccess.framework/DigitalAccess
540: /System/Library/PrivateFrameworks/DistributedEvaluation.framework/DistributedEvaluation
541: /System/Library/PrivateFrameworks/DocumentCamera.framework/DocumentCamera
542: /System/Library/PrivateFrameworks/DocumentManager.framework/DocumentManager
543: /System/Library/PrivateFrameworks/DocumentManagerCore.framework/DocumentManagerCore
544: /System/Library/PrivateFrameworks/DragUI.framework/DragUI
545: /System/Library/PrivateFrameworks/EAP8021X.framework/EAP8021X
546: /System/Library/PrivateFrameworks/EmailAddressing.framework/EmailAddressing
547: /System/Library/PrivateFrameworks/Engram.framework/Engram
548: /System/Library/PrivateFrameworks/ExtensionFoundation.framework/ExtensionFoundation
549: /System/Library/PrivateFrameworks/FSEvents.framework/FSEvents
550: /System/Library/PrivateFrameworks/FTAWD.framework/FTAWD
551: /System/Library/PrivateFrameworks/FTClientServices.framework/FTClientServices
552: /System/Library/PrivateFrameworks/FaceCore.framework/FaceCore
553: /System/Library/PrivateFrameworks/FeatureFlagsSupport.framework/FeatureFlagsSupport
554: /System/Library/PrivateFrameworks/FeedbackLogger.framework/FeedbackLogger
555: /System/Library/PrivateFrameworks/FontServices.framework/libFontParser.dylib
556: /System/Library/PrivateFrameworks/FontServices.framework/libGSFont.dylib
557: /System/Library/PrivateFrameworks/FontServices.framework/libGSFontCache.dylib
558: /System/Library/PrivateFrameworks/FontServices.framework/libhvf.dylib
559: /System/Library/PrivateFrameworks/Futhark.framework/Futhark
560: /System/Library/PrivateFrameworks/GameCenterUICore.framework/GameCenterUICore
561: /System/Library/PrivateFrameworks/GameKitServices.framework/GameKitServices
562: /System/Library/PrivateFrameworks/GenerationalStorage.framework/GenerationalStorage
563: /System/Library/PrivateFrameworks/GraphVisualizer.framework/GraphVisualizer
564: /System/Library/PrivateFrameworks/HID.framework/HID
565: /System/Library/PrivateFrameworks/HSAAuthentication.framework/HSAAuthentication
566: /System/Library/PrivateFrameworks/Heimdal.framework/Heimdal
567: /System/Library/PrivateFrameworks/HomeSharing.framework/HomeSharing
568: /System/Library/PrivateFrameworks/IDSKVStore.framework/IDSKVStore
569: /System/Library/PrivateFrameworks/IMSharedUI.framework/IMSharedUI
570: /System/Library/PrivateFrameworks/IMTranscoding.framework/IMTranscoding
571: /System/Library/PrivateFrameworks/IOKitten.framework/IOKitten
572: /System/Library/PrivateFrameworks/IOSurfaceAccelerator.framework/IOSurfaceAccelerator
573: /System/Library/PrivateFrameworks/IdleTimerServices.framework/IdleTimerServices
574: /System/Library/PrivateFrameworks/IncomingCallFilter.framework/IncomingCallFilter
575: /System/Library/PrivateFrameworks/InertiaCam.framework/InertiaCam
576: /System/Library/PrivateFrameworks/IntentsFoundation.framework/IntentsFoundation
577: /System/Library/PrivateFrameworks/InternationalTextSearch.framework/InternationalTextSearch
578: /System/Library/PrivateFrameworks/IntlPreferences.framework/IntlPreferences
579: /System/Library/PrivateFrameworks/Jet.framework/Jet
580: /System/Library/PrivateFrameworks/LegacyGameKit.framework/LegacyGameKit
581: /System/Library/PrivateFrameworks/LimitAdTracking.framework/LimitAdTracking
582: /System/Library/PrivateFrameworks/LinguisticData.framework/LinguisticData
583: /System/Library/PrivateFrameworks/LocalAuthenticationPrivateUI.framework/LocalAuthenticationPrivateUI
584: /System/Library/PrivateFrameworks/MOVStreamIO.framework/MOVStreamIO
585: /System/Library/PrivateFrameworks/Marco.framework/Marco
586: /System/Library/PrivateFrameworks/MediaLibraryCore.framework/MediaLibraryCore
587: /System/Library/PrivateFrameworks/MediaPlatform.framework/MediaPlatform
588: /System/Library/PrivateFrameworks/MetalTools.framework/MetalTools
589: /System/Library/PrivateFrameworks/MetricsKit.framework/MetricsKit
590: /System/Library/PrivateFrameworks/MobileBluetooth.framework/MobileBluetooth
591: /System/Library/PrivateFrameworks/MobileObliteration.framework/MobileObliteration
592: /System/Library/PrivateFrameworks/MobileSystemServices.framework/MobileSystemServices
593: /System/Library/PrivateFrameworks/NanoResourceGrabber.framework/NanoResourceGrabber
594: /System/Library/PrivateFrameworks/NanoSystemSettings.framework/NanoSystemSettings
595: /System/Library/PrivateFrameworks/Netrb.framework/Netrb
596: /System/Library/PrivateFrameworks/NetworkStatistics.framework/NetworkStatistics
597: /System/Library/PrivateFrameworks/OAuth.framework/OAuth
598: /System/Library/PrivateFrameworks/OTSVG.framework/OTSVG
599: /System/Library/PrivateFrameworks/PBBridgeSupport.framework/PBBridgeSupport
600: /System/Library/PrivateFrameworks/ParsecSubscriptionServiceSupport.framework/ParsecSubscriptionServiceSupport
601: /System/Library/PrivateFrameworks/Pasteboard.framework/Pasteboard
602: /System/Library/PrivateFrameworks/PersonaKit.framework/PersonaKit
603: /System/Library/PrivateFrameworks/PersonaUI.framework/PersonaUI
604: /System/Library/PrivateFrameworks/PhoneNumbers.framework/PhoneNumbers
605: /System/Library/PrivateFrameworks/PhotosImagingFoundation.framework/PhotosImagingFoundation
606: /System/Library/PrivateFrameworks/PhysicsKit.framework/PhysicsKit
607: /System/Library/PrivateFrameworks/PointerUIServices.framework/PointerUIServices
608: /System/Library/PrivateFrameworks/ProgressUI.framework/ProgressUI
609: /System/Library/PrivateFrameworks/PrototypeToolsUI.framework/PrototypeToolsUI
610: /System/Library/PrivateFrameworks/QuickLookSupport.framework/QuickLookSupport
611: /System/Library/PrivateFrameworks/RTCReporting.framework/RTCReporting
612: /System/Library/PrivateFrameworks/RemoteTextInput.framework/RemoteTextInput
613: /System/Library/PrivateFrameworks/RemoteUI.framework/RemoteUI
614: /System/Library/PrivateFrameworks/RevealCore.framework/RevealCore
615: /System/Library/PrivateFrameworks/SDAPI.framework/SDAPI
616: /System/Library/PrivateFrameworks/SEService.framework/SEService
617: /System/Library/PrivateFrameworks/SceneIntelligence.framework/SceneIntelligence
618: /System/Library/PrivateFrameworks/ScreenshotServices.framework/ScreenshotServices
619: /System/Library/PrivateFrameworks/SignpostCollection.framework/SignpostCollection
620: /System/Library/PrivateFrameworks/SignpostMetrics.framework/SignpostMetrics
621: /System/Library/PrivateFrameworks/SignpostSupport.framework/SignpostSupport
622: /System/Library/PrivateFrameworks/SoftLinking.framework/SoftLinking
623: /System/Library/PrivateFrameworks/StorageSettings.framework/StorageSettings
624: /System/Library/PrivateFrameworks/StreamingZip.framework/StreamingZip
625: /System/Library/PrivateFrameworks/SymptomDiagnosticReporter.framework/SymptomDiagnosticReporter
626: /System/Library/PrivateFrameworks/Symptoms.framework/Frameworks/SymptomPresentationFeed.framework/SymptomPresentationFeed
627: /System/Library/PrivateFrameworks/TCC.framework/TCC
628: /System/Library/PrivateFrameworks/TextureIO.framework/TextureIO
629: /System/Library/PrivateFrameworks/TipKit.framework/TipKit
630: /System/Library/PrivateFrameworks/TipsUI.framework/TipsUI
631: /System/Library/PrivateFrameworks/TransparencyDetailsView.framework/TransparencyDetailsView
632: /System/Library/PrivateFrameworks/URLFormatting.framework/URLFormatting
633: /System/Library/PrivateFrameworks/USDKit.framework/USDKit
634: /System/Library/PrivateFrameworks/UsageTracking.framework/UsageTracking
635: /System/Library/PrivateFrameworks/VoiceTrigger.framework/VoiceTrigger
636: /System/Library/PrivateFrameworks/WatchdogClient.framework/WatchdogClient
637: /System/Library/PrivateFrameworks/WebCore.framework/Frameworks/libwebrtc.dylib
638: /System/Library/PrivateFrameworks/WebUI.framework/WebUI
639: /System/Library/PrivateFrameworks/WirelessCoexManager.framework/WirelessCoexManager
640: /System/Library/PrivateFrameworks/XCTTargetBootstrap.framework/XCTTargetBootstrap
641: /System/Library/PrivateFrameworks/caulk.framework/caulk
642: /System/Library/PrivateFrameworks/iAdServices.framework/iAdServices
643: /System/Library/PrivateFrameworks/kperf.framework/kperf
644: /System/Library/PrivateFrameworks/kperfdata.framework/kperfdata
645: /System/Library/PrivateFrameworks/libEDR.framework/libEDR
646: /System/Library/PrivateFrameworks/perfdata.framework/perfdata
647: /System/Library/PrivateFrameworks/vCard.framework/vCard
648: /usr/lib/libAWDSupport.dylib
649: /usr/lib/libAWDSupportFramework.dylib
650: /usr/lib/libAudioStatistics.dylib
651: /usr/lib/libCRFSuite.dylib
652: /usr/lib/libCTGreenTeaLogger.dylib
653: /usr/lib/libChineseTokenizer.dylib
654: /usr/lib/libIOReport.dylib
655: /usr/lib/libMatch.1.dylib
656: /usr/lib/libParallelCompression.dylib
657: /usr/lib/libThaiTokenizer.dylib
658: /usr/lib/libapp_launch_measurement.dylib
659: /usr/lib/libapple_nghttp2.dylib
660: /usr/lib/libate.dylib
661: /usr/lib/libbsm.0.dylib
662: /usr/lib/libbz2.1.0.dylib
663: /usr/lib/libcharset.1.dylib
664: /usr/lib/libcmph.dylib
665: /usr/lib/libcompression.dylib
666: /usr/lib/libcoretls.dylib
667: /usr/lib/libcoretls_cfhelpers.dylib
668: /usr/lib/libcupolicy.dylib
669: /usr/lib/libdns_services.dylib
670: /usr/lib/libedit.3.dylib
671: /usr/lib/libenergytrace.dylib
672: /usr/lib/libexpat.1.dylib
673: /usr/lib/libgermantok.dylib
674: /usr/lib/libheimdal-asn1.dylib
675: /usr/lib/libiconv.2.dylib
676: /usr/lib/liblangid.dylib
677: /usr/lib/liblockdown.dylib
678: /usr/lib/liblzma.5.dylib
679: /usr/lib/libmecab.dylib
680: /usr/lib/libmecabra.dylib
681: /usr/lib/libmis.dylib
682: /usr/lib/libnetworkextension.dylib
683: /usr/lib/libpcap.A.dylib
684: /usr/lib/libperfcheck.dylib
685: /usr/lib/libprequelite.dylib
686: /usr/lib/libprotobuf-lite.dylib
687: /usr/lib/libprotobuf.dylib
688: /usr/lib/libresolv.9.dylib
689: /usr/lib/libsandbox.1.dylib
690: /usr/lib/libspindump.dylib
691: /usr/lib/libutil.dylib
692: /usr/lib/libxml2.2.dylib
693: /usr/lib/libxslt.1.dylib
694: /usr/lib/libz.1.dylib
695: /usr/lib/swift/libswiftAVFoundation.dylib
696: /usr/lib/swift/libswiftAccelerate.dylib
697: /usr/lib/swift/libswiftAssetsLibrary.dylib
698: /usr/lib/swift/libswiftCompression.dylib
699: /usr/lib/swift/libswiftContacts.dylib
700: /usr/lib/swift/libswiftCoreAudio.dylib
701: /usr/lib/swift/libswiftCoreData.dylib
702: /usr/lib/swift/libswiftCoreFoundation.dylib
703: /usr/lib/swift/libswiftCoreImage.dylib
704: /usr/lib/swift/libswiftCoreLocation.dylib
705: /usr/lib/swift/libswiftCoreMIDI.dylib
706: /usr/lib/swift/libswiftCoreML.dylib
707: /usr/lib/swift/libswiftCoreMedia.dylib
708: /usr/lib/swift/libswiftDarwin.dylib
709: /usr/lib/swift/libswiftGLKit.dylib
710: /usr/lib/swift/libswiftGameplayKit.dylib
711: /usr/lib/swift/libswiftMediaPlayer.dylib
712: /usr/lib/swift/libswiftMetal.dylib
713: /usr/lib/swift/libswiftMetalKit.dylib
714: /usr/lib/swift/libswiftModelIO.dylib
715: /usr/lib/swift/libswiftPhotos.dylib
716: /usr/lib/swift/libswiftQuartzCore.dylib
717: /usr/lib/swift/libswiftSceneKit.dylib
718: /usr/lib/swift/libswiftSpriteKit.dylib
719: /usr/lib/swift/libswiftVision.dylib
720: /usr/lib/swift/libswiftWebKit.dylib
721: /usr/lib/swift/libswiftos.dylib
722: /usr/lib/swift/libswiftsimd.dylib
723: /usr/lib/system/libcache.dylib
724: /usr/lib/system/libcommonCrypto.dylib
725: /usr/lib/system/libcompiler_rt.dylib
726: /usr/lib/system/libcopyfile.dylib
727: /usr/lib/system/liblaunch.dylib
728: /usr/lib/system/libmacho.dylib
729: /usr/lib/system/libremovefile.dylib
730: /usr/lib/system/libsystem_blocks.dylib
731: /usr/lib/system/libsystem_collections.dylib
732: /usr/lib/system/libsystem_configuration.dylib
733: /usr/lib/system/libsystem_containermanager.dylib
734: /usr/lib/system/libsystem_coreservices.dylib
735: /usr/lib/system/libsystem_darwin.dylib
736: /usr/lib/system/libsystem_dnssd.dylib
737: /usr/lib/system/libsystem_featureflags.dylib
738: /usr/lib/system/libsystem_m.dylib
739: /usr/lib/system/libsystem_platform.dylib
740: /usr/lib/system/libsystem_product_info_filter.dylib
741: /usr/lib/system/libsystem_pthread.dylib
742: /usr/lib/system/libsystem_sandbox.dylib
743: /usr/lib/system/libunwind.dylib
744: /usr/lib/system/libxpc.dylib
745: /System/Library/PrivateFrameworks/SpotlightLinguistics.framework/SpotlightLinguistics


{"ProcessBundleID":"com.beeasy.shopee.my","ProcessName":"ShopeeMY","Culprit":"Shadow.dylib"}
```

**Comment by jjolano** [comment]
Seems something isn't getting hooked properly by Substitute.. I assume you have the latest Substitute?

**Comment by keldey** [comment]
You could try disable all tweaks in iCleaner’s Cydia Substrate Addon except for Shadow and the essentials to check for conflicting tweak. Or try reinstall app. The SG version of Shopee works for me too using ‘File System’, ‘Loaded Modules’ and ‘Runtime Class Lookups’ options, and I can go into ShopeePay option

**Comment by yur1xpp** [comment]
@jjolano I believeI do, it says version 2.3.1. Could this be an arm64 issue?

@keldey What iPhone you tested on? I disabled all tweaks except shadow, did a userspace reboot, the app still crash. Perhaps this is an issue on arm64, if you're using arm64e device.

**Comment by yur1xpp** [comment]
I just tried with another app on same system, [Lazada](https://apps.apple.com/us/app/lazada-12-12-sale/id785385147), I got the same crash whenever loaded modules enabled. Seems like not an isolated issue.

Here's the IPA if you wanted to test it out:
https://www.dropbox.com/s/535jnkmxyty55uy/decrypted-lazada-907.15.1.ipa?dl=0

**Comment by jjolano** [comment]
@yur1xpp I also use an iPhone X on 14.3, but I have libhooker rather than Substitute. My other device is an iPad 7 on 15.7.1 (palera1n) with Substitute, latest version. App is working just fine on both setups.

Lazada seems to outright crash regardless of tweaks with a library not loaded error, I think that IPA might be faulty

**Comment by jjolano** [comment]
There is one thing I can try for next update if Loaded Modules is all that's needed. If it still doesn't work I'm not sure what I can do since the hooks themselves are pretty barebones as much as it could be.

**Comment by jjolano** [comment]
Please try version 3.3.5. I moved the potentially problematic hook into Loaded Modules (Extra), so hopefully that option is not needed for the app in terms of bypassing detection.

**Comment by yur1xpp** [comment]
Just tried it, it works! Payment method also works fine without enabling the extras. Thanks very much for this man, appreciate it.

**Comment by jjolano** [comment]
Thats great to hear!
